name: Build deb

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    permissions:
      contents: write
    steps:
      - name: Install dep
        run: apt update && apt install git python3-pip dpkg-dev -y
      - uses: actions/checkout@v4
      - name: Pull pmbootstrap
        run: |
          git clone https://gitlab.com/postmarketos/pmbootstrap
          mv package/debian ./pmbootstrap
      - name: Build deb
        run: dpkg-buildpackage -b -us -uc
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: ./*.deb
