name: Build rootfs

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup pmbootstrap
        run: |
          #sudo mv -v pmaports /home/runner/
          git clone https://gitlab.com/postmarketOS/pmbootstrap --depth=1
          cd pmbootstrap
          chmod +x pmbootstrap.py
          #sudo rm /usr/bin/pmbootstrap
          #sudo ln -sfv ./pmbootstrap.py /usr/bin/pmbootstrap
          
      - name: Initialize pmbootstrap
        run: |
           sudo aria2c  https://github.com/sekaimoe/pmos_ci_build/raw/main/device/raphael/pmbootstrap_v3.cfg
           sudo mv pmbootstrap_v3.cfg -v /home/runner/.config/pmbootstrap_v3.cfg
           sudo chmod 777 -v /home/runner/.config/pmbootstrap_v3.cfg
           yes '' | ./pmbootstrap/pmbootstrap.py --details-to-stdout init
           #printf "%s\n" "edge" "xiaomi" "raphael" "user" "xfce4" "n" "none" "en_US" "xiaomi-raphael" "y" | ./pmbootstrap/pmbootstrap.py -q init

      - name: Build rootfs
        run: yes '123456' | ./pmbootstrap/pmbootstrap.py --details-to-stdout install --android-recovery-zip --recovery-install-partition=data

      - name: Export rootfs
        if: github.event_name == 'workflow_dispatch'
        run: ./pmbootstrap/pmbootstrap.py --details-to-stdout export

      - name: Upload log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: /home/runner/.var/local/pmbootstrap/log.txt


      - name: Upload rootfs
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: /tmp/postmarketOS-export/*
